api_secret: '' # Should be
jwt_algorithm: 'HS256'
user_session_timeout: 168
debug_mode: False

uri_prefix: ''

db:
  server: "localhost"
  port: 5432
  name:
  login:
  password:
  pool_size: 25
  max_overflow: 100
