api_secret: '' # Should be
jwt_algorithm: 'HS256'
user_session_timeout: 168
debug_mode: False
static_path: '/home/backdev/data/'
static_url: 'https://metaads.team/data/'
uri_prefix: ''
nft_api_url: 'https://api.nft.storage/upload'
nft_api_key: ''
max_timeslot_duration: 60

db:
  server: "localhost"
  port: 5432
  name:
  login:
  password:
  pool_size: 25
  max_overflow: 100
