"""adspot jump_url

Revision ID: 81e60cacccb2
Revises: c2820189b82d
Create Date: 2022-02-17 12:55:20.565844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e60cacccb2'
down_revision = 'c2820189b82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adspots', sa.Column('jump_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adspots', 'jump_url')
    # ### end Alembic commands ###
