"""web3token auth

Revision ID: 95ca4ee12c74
Revises: 15afb1722e18
Create Date: 2022-02-15 19:46:08.412236

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '95ca4ee12c74'
down_revision = '15afb1722e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('advertisers', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisers', sa.Column(
        'password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=False))
    op.alter_column('advertisers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
