"""playbacks.processed_at

Revision ID: a445c0a5411f
Revises: 8722a94ae8d1
Create Date: 2022-02-02 12:12:49.749852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a445c0a5411f'
down_revision = '8722a94ae8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbacks', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbacks', 'processed_at')
    # ### end Alembic commands ###
