"""added adspots.status

Revision ID: bf4ef4bdd392
Revises: 95ca4ee12c74
Create Date: 2022-02-16 15:43:59.776442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4ef4bdd392'
down_revision = '95ca4ee12c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adspots', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adspots', 'active')
    # ### end Alembic commands ###
