"""nallable advert urls

Revision ID: c2820189b82d
Revises: bf4ef4bdd392
Create Date: 2022-02-16 15:30:00.362442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2820189b82d'
down_revision = 'bf4ef4bdd392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adspots', 'publish_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('adspots', 'stop_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('adspots', 'stop_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('adspots', 'publish_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
