"""publisher

Revision ID: ebe1ba8fe2a5
Revises: dbb698a6db0b
Create Date: 2022-01-25 15:11:17.278078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe1ba8fe2a5'
down_revision = 'dbb698a6db0b'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishers')
    # ### end Alembic commands ###
